version: 2.1

executors:
  docker-executor:
    machine:
      image: ubuntu-2204:current  # Image of Ubuntu 22.04 with the latest version
    
jobs:
  build:
    executor: docker-executor
    steps:
      # Step 1: Checkout the code from the repository
      - checkout

      # Step 3: Build the Docker image
      - run:
          name: Build Docker Image
          command: docker build -t $DOCKER_USERNAME/node-js-sample:latest .

      # Step 4: Run the Docker container on the correct port
      - run:
          name: Run Docker Container
          command: docker run -d -p 3000:8080 --name node-js-container node-js-sample

      # Step 5: Wait for the app to start (increased sleep time to ensure app is fully started)
      - run:
          name: Wait for Docker container to start
          command: sleep 10

      # Step 6: Test if the app is running and responding on the expected route
      - run:
          name: Test if Docker container is answering on the expected route
          command: |
            curl -f http://localhost:3000 || (echo 'App did not respond correctly' && exit 1)

       # Log in to DockerHub
      - run:
          name: Log in to Docker Hub
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      # Push Docker image to Docker Hub if tests pass
      - run:
          name: Push Docker Image to Docker Hub
          command: 
            docker push node-js-sample

workflows:
  version: 2
  build:
    jobs:
      - build
