version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:18
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image
          command: |
            docker build -t node-js-sample .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
